stages:
  - lint

eslint:
  image: node:latest
  stage: lint
  script:
    - npm i
    - npm run lint
  cache:
    paths:
      - node_modules/

phpcs:
  image: php:7.1
  stage: lint
  script:
    - php composer.phar test
  cache:
    paths:
      - vendor/
      - composer.phar

  before_script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

